### ISSUE TITLE
New feature for adding Docker & Docker Compose

### ISSUE THREAD

**Issue by aminnairi** [SkyDogzz/myges-notification#1]
It would be awesome to have a Docker Container in order to be able to use this script on:
- A fixed version of Node.js (and prevent conflicts between different operating system's Node.js versions)
- Run Cron tasks without having to install Cron on our operating system
- Be able to run this script easily on Windows, Mac & UNIX-like operating systems

This could look like this (this is not a working example).

```bash
touch docker-compose.yaml
```

```yaml
version: "3"

services:
  node:
    build: path/to/node/Dockerfile
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    volumes:
      - .:/home/node
```

This would mean running this script with these commands

```bash
docker compose up --detach --build
docker compose exec node path/to/script.js
```

What do you think?
